package google

//TestResult Generated by https://quicktype.io
type TestResult struct {
	Tests      int64        `json:"tests"`
	Failures   int64        `json:"failures"`
	Disabled   int64        `json:"disabled"`
	Errors     int64        `json:"errors"`
	Timestamp  *string      `json:"timestamp,omitempty"`
	Time       string       `json:"time"`
	Name       string       `json:"name"`
	Testsuites []TestResult `json:"testsuites"`
	Testsuite  []Testsuite  `json:"testsuite"`
}

//Testsuite Generated by https://quicktype.io
type Testsuite struct {
	Name      string    `json:"name"`
	Status    string    `json:"status"`
	Time      string    `json:"time"`
	Classname string    `json:"classname"`
	Failures  []Failure `json:"failures"`
}

//Failure Generated by https://quicktype.io
type Failure struct {
	Failure string `json:"failure"`
	Type    string `json:"type"`
}
